feat: criação das rotas
Liv-new-rizon/squad-3-reforca-o-bem-web pull request #5
Opened 2024-10-23 20:30 UTC by mathmota14

Pull request para a adição das rotas

2024-10-23 21:59 UTC, aLiviaMs requested changes

2024-10-23 21:59 UTC, aLiviaMs commented on src/app/app-routing.module.ts
> +  { path: 'student-registration', component: StudentRegistrationComponent },
O usuario precisa estar logado na aplicacao para acessar essa pagina, correto?
Para isso precisa colocar o authGuard pra validar q só assim ele poderá acessar aqui

2024-10-23 21:59 UTC, aLiviaMs commented on src/app/pages/signup/signup.component.ts
> +    }).subscribe(() => {
No Angular, quando você se inscreve (subscribe) em um Observable, essa inscrição permanece ativa até que você explicitamente se desinscreva ou até que o componente seja destruído. Se você não gerenciar corretamente essas inscrições, pode levar a problemas de vazamento de memória e comportamentos inesperados na aplicação.

Para corrigir isso, você tem algumas opções:

1. Usar o operador take(1):

```ts
this.dialogService.openInfoDialog({
  title: 'Cadastro prévio realizado com sucesso',
  buttonText: 'Fechar'
}).pipe(take(1)).subscribe(() => {
  this.navigateToLogin();
});
```
Isso garante que a inscrição seja automaticamente cancelada após a primeira emissão.


2. Armazenar a inscrição e cancelá-la no ngOnDestroy:
Usar um Subject para o destroy$ com o operador takeUntil é uma prática muito eficaz e comum no Angular para gerenciar inscrições. Essa abordagem permite que você gerencie múltiplas inscrições de forma limpa e eficiente.

```ts
private _destroy$ = new Subject<void>();

public ngOnInit() {
    this.dialogService.openInfoDialog({
      title: 'Cadastro prévio realizado com sucesso',
      buttonText: 'Fechar'
    }).pipe(
      takeUntil(this.destroy$)
    ).subscribe(() => {
      this.navigateToLogin();
    });
}

public ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
}
```

3. Usar o AsyncPipe no template (se aplicável):
Isso gerencia automaticamente a inscrição e desincrição.

Escolha a abordagem que melhor se adequa ao seu caso de uso específico. No caso de dialogs, a opção 1 usando take(1) geralmente é suficiente, pois você normalmente só espera uma única emissão quando o diálogo é fechado.

2024-10-24 00:51 UTC, Lauragpse commented
pode analisar se a logica para a criação da mascara para a data esta correta?, o arquivo scss vou arrumar quando tiver os outros inputs adicionados

2024-10-24 10:32 UTC, aLiviaMs commented
> pode analisar se a logica para a criação da mascara para a data esta correta?, o arquivo scss vou arrumar quando tiver os outros inputs adicionados

@Lauragpse , Retire seu commit da branch do @mathmota14 .
E abra o seu proprio PR com as mascaras, não é assim que atuamos com o gitflow.
Vc desenvolveu uma funcionalidade e ele outra.
Se vc precisa de coisas da branch de criacão de rotas vc pode criar uma branch nova A PARTIR desta branch, mas sinceramente para criação apenas de mascáras isso não era necessário.

Quando vc está em uma branch e faz git -b checkout <nova-branch> vc cria uma branch para vc com o histórico de commits da branch que vc estava, não necessariamente funciona só para a develop, é ESSENCIAL vcs entenderem o fluxo do git.

2024-10-24 10:55 UTC, aLiviaMs commented
> pode analisar se a logica para a criação da mascara para a data esta correta?, o arquivo scss vou arrumar quando tiver os outros inputs adicionados

@Lauragpse, vou ser boazinha e ajudar com um passo a passo de como fazer um cherry-pick.



```md
#1. Crie uma nova branch com o histórico atual.
`git branch <nome-da-branch>`

# 2. Identificar o commit na branch original
use o comando:`git log`
Este comando mostrará o histórico de commits. Anote o hash do commit que você deseja mover.
**Dica:** Você pode usar `git log --oneline` para uma visualização mais compacta.

*** Formato do log que virá: `<hash-do-commit> <mensagem-do commit>`

# 3. Remover o commit da branch atual
`git revert <hash-do-commit>`
Isso criará um novo commit que desfaz as alterações do commit original.
(resolva os conflitos caso exista, e faça o commit nesta branch com o revert.)

e dps de checkout na branch q vc criou anteriormente.


caso n funcione é possivel fazer um cherry-pick do seu commit, o git é um histórico, nada será perdido, fiquem tranquilos.
git cherry-pick é um comando poderoso no Git que permite você copiar um commit específico de uma branch para outra. É como "colher" (pick) um commit específico e aplicá-lo em outro lugar. Isso é útil quando você quer trazer mudanças específicas de uma branch para outra sem mesclar a branch inteira.
Execução do cherry-pick:
git cherry-pick <hash-do-commit>

2024-10-24 10:59 UTC, aLiviaMs commented
Dito tudo isso, apesar do seu PR @mathmota14 estar pronto para ser aprovado, vou REPROVAR este PR até que o revert dos commits da @Lauragpse e se necessário, ela mesma abra um PR.
Não irei analisar o código da máscara neste PR.

2024-10-24 10:59 UTC, closed without merging